/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BookSearchPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian13 = require("obsidian");

// src/apis/base_api.ts
var import_obsidian2 = require("obsidian");

// src/apis/google_books_api.ts
var import_obsidian = require("obsidian");
var ISBN_REGEX = /^(97[89])?\d{9}(\d|X)$/;
var _GoogleBooksApi = class _GoogleBooksApi {
  constructor(localePreference, enableCoverImageEdgeCurl, apiKey) {
    this.localePreference = localePreference;
    this.enableCoverImageEdgeCurl = enableCoverImageEdgeCurl;
    this.apiKey = apiKey;
  }
  getLanguageRestriction(local) {
    return local === "default" ? import_obsidian.moment.locale() : local;
  }
  buildSearchParams(query, options) {
    const params = {
      q: query,
      maxResults: _GoogleBooksApi.MAX_RESULTS,
      printType: _GoogleBooksApi.PRINT_TYPE
    };
    if (!ISBN_REGEX.test(query.trim())) {
      params["langRestrict"] = this.getLanguageRestriction((options == null ? void 0 : options.locale) || this.localePreference);
    }
    if (this.apiKey) {
      params["key"] = this.apiKey;
    }
    return params;
  }
  async getByQuery(query, options) {
    try {
      const params = this.buildSearchParams(query, options);
      const searchResults = await apiGet("https://www.googleapis.com/books/v1/volumes", params);
      if (!(searchResults == null ? void 0 : searchResults.totalItems))
        return [];
      return searchResults.items.map(({ volumeInfo }) => this.createBookItem(volumeInfo));
    } catch (error) {
      console.warn(error);
      throw error;
    }
  }
  extractISBNs(industryIdentifiers) {
    var _a;
    return (_a = industryIdentifiers == null ? void 0 : industryIdentifiers.reduce(
      (result, item) => {
        const isbnType = item.type === "ISBN_10" /* Isbn10 */ ? "isbn10" : "isbn13";
        result[isbnType] = item.identifier.trim();
        return result;
      },
      {}
    )) != null ? _a : {};
  }
  extractBasicBookInfo(item) {
    var _a, _b, _c, _d;
    return {
      title: item.title,
      subtitle: item.subtitle,
      author: this.formatList(item.authors),
      authors: item.authors || [],
      category: this.formatList(item.categories),
      categories: item.categories || [],
      publisher: item.publisher,
      totalPage: item.pageCount,
      coverUrl: this.setCoverImageEdgeCurl((_b = (_a = item.imageLinks) == null ? void 0 : _a.thumbnail) != null ? _b : "", this.enableCoverImageEdgeCurl),
      coverSmallUrl: this.setCoverImageEdgeCurl((_d = (_c = item.imageLinks) == null ? void 0 : _c.smallThumbnail) != null ? _d : "", this.enableCoverImageEdgeCurl),
      publishDate: item.publishedDate || "",
      description: item.description,
      link: item.canonicalVolumeLink || item.infoLink,
      previewLink: item.previewLink
    };
  }
  createBookItem(item) {
    const book = {
      title: "",
      subtitle: "",
      author: "",
      authors: [],
      category: "",
      categories: [],
      publisher: "",
      publishDate: "",
      totalPage: "",
      coverUrl: "",
      coverSmallUrl: "",
      description: "",
      link: "",
      previewLink: "",
      ...this.extractBasicBookInfo(item),
      ...this.extractISBNs(item.industryIdentifiers)
    };
    return book;
  }
  formatList(list) {
    var _a;
    return list && list.length > 1 ? list.map((item) => item.trim()).join(", ") : (_a = list == null ? void 0 : list[0]) != null ? _a : "";
  }
  setCoverImageEdgeCurl(url, enabled) {
    return enabled ? url : url.replace("&edge=curl", "");
  }
  static convertGoogleBookImageURLSize(url, zoom) {
    return url.replace(/(&zoom)=\d/, `$1=${zoom}`);
  }
};
_GoogleBooksApi.MAX_RESULTS = 40;
_GoogleBooksApi.PRINT_TYPE = "books";
var GoogleBooksApi = _GoogleBooksApi;

// src/apis/naver_books_api.ts
var NaverBooksApi = class {
  constructor(clientId, clientSecret) {
    this.clientId = clientId;
    this.clientSecret = clientSecret;
  }
  async getByQuery(query) {
    try {
      const params = {
        query,
        display: 50,
        sort: "sim"
      };
      const header = {
        "X-Naver-Client-Id": this.clientId,
        "X-Naver-Client-Secret": this.clientSecret
      };
      const searchResults = await apiGet(
        "https://openapi.naver.com/v1/search/book.json",
        params,
        header
      );
      if (!(searchResults == null ? void 0 : searchResults.total)) {
        return [];
      }
      return searchResults.items.map((item) => this.createBookItem(item));
    } catch (error) {
      console.warn(error);
      throw error;
    }
  }
  createBookItem(item) {
    var _a, _b;
    return {
      title: item.title,
      author: item.author,
      publisher: item.publisher,
      coverUrl: item.image,
      publishDate: ((_a = item.pubdate) == null ? void 0 : _a.slice(0, 4)) || "",
      link: item.link,
      description: item.description,
      isbn: item.isbn,
      ...((_b = item.isbn) == null ? void 0 : _b.length) >= 13 ? { isbn13: item.isbn } : { isbn10: item.isbn }
    };
  }
};

// src/apis/base_api.ts
var ConfigurationError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "ConfigurationError";
  }
};
function factoryServiceProvider(settings) {
  switch (settings.serviceProvider) {
    case "google" /* google */:
      return new GoogleBooksApi(settings.localePreference, settings.enableCoverImageEdgeCurl, settings.apiKey);
    case "naver" /* naver */:
      validateNaverSettings(settings);
      return new NaverBooksApi(settings.naverClientId, settings.naverClientSecret);
    default:
      throw new Error("Unsupported service provider.");
  }
}
function validateNaverSettings(settings) {
  if (!settings.naverClientId || !settings.naverClientSecret) {
    throw new ConfigurationError('\uB124\uC774\uBC84 \uAC1C\uBC1C\uC790\uC13C\uD130\uC5D0\uC11C "Client ID"\uC640 "Client Secret"\uB97C \uBC1C\uAE09\uBC1B\uC544 \uC124\uC815\uD574\uC8FC\uC138\uC694.');
  }
}
var REQUEST_TIMEOUT_MS = 15e3;
function requestWithTimeout(options, ms) {
  let timeoutId;
  const timeout = new Promise((_, reject) => {
    timeoutId = activeWindow.setTimeout(
      () => reject(Object.assign(new Error(`Request timed out after ${ms} ms`), { timeout: true })),
      ms
    );
  });
  return Promise.race([(0, import_obsidian2.requestUrl)(options), timeout]).finally(() => activeWindow.clearTimeout(timeoutId));
}
async function apiGet(url, params = {}, headers) {
  const apiURL = new URL(url);
  appendQueryParams(apiURL, params);
  const requestOptions = {
    url: apiURL.href,
    method: "GET",
    headers: {
      Accept: "*/*",
      "Content-Type": "application/json; charset=utf-8",
      ...headers
    }
  };
  let lastError;
  for (let attempt = 0; attempt < 4; attempt++) {
    try {
      const res = await requestWithTimeout(requestOptions, REQUEST_TIMEOUT_MS);
      return res.json;
    } catch (error) {
      lastError = error;
      const status = error.status;
      const message = error instanceof Error ? error.message : "";
      const isRetryable = status === 503 || message.includes("503");
      if (attempt < 3 && isRetryable) {
        await new Promise((resolve) => activeWindow.setTimeout(resolve, 1e3 * Math.pow(2, attempt)));
      } else {
        throw error;
      }
    }
  }
  throw lastError;
}
function appendQueryParams(url, params) {
  Object.entries(params).forEach(([key, value]) => {
    url.searchParams.append(key, value.toString());
  });
}

// src/utils/utils.ts
var import_obsidian3 = require("obsidian");
var NUMBER_REGEX = /^-?[0-9]*$/;
var DATE_REGEX = /{{DATE(\+-?[0-9]+)?}}/;
var DATE_REGEX_FORMATTED = /{{DATE:([^}\n\r+]*)(\+-?[0-9]+)?}}/;
function replaceIllegalFileNameCharactersInString(text) {
  return text.replace(/[\\#%&{}/*<>$":@.?|]/g, "").replace(/\s+/g, " ");
}
function makeFileName(book, fileNameFormat, extension = "md") {
  let result;
  if (fileNameFormat) {
    result = replaceVariableSyntax(book, replaceDateInString(fileNameFormat));
  } else {
    result = !book.author ? book.title : `${book.title} - ${book.author}`;
  }
  return replaceIllegalFileNameCharactersInString(result) + `.${extension}`;
}
function safeToString(value) {
  if (value == null)
    return "";
  if (typeof value === "string")
    return value;
  if (typeof value === "number" || typeof value === "boolean")
    return String(value);
  return JSON.stringify(value);
}
function changeSnakeCase(book) {
  return Object.entries(book).reduce((acc, [key, value]) => {
    acc[camelToSnakeCase(key)] = value;
    return acc;
  }, {});
}
function applyDefaultFrontMatter(book, frontmatter, keyType = "Snake Case" /* snakeCase */) {
  const frontMater = keyType === "Camel Case" /* camelCase */ ? { ...book } : changeSnakeCase(book);
  const extraFrontMatter = typeof frontmatter === "string" ? parseFrontMatter(frontmatter) : frontmatter;
  for (const key in extraFrontMatter) {
    const raw = extraFrontMatter[key];
    const value = raw != null ? safeToString(raw).trim() : "";
    if (frontMater[key] && frontMater[key] !== value) {
      frontMater[key] = `${safeToString(frontMater[key])}, ${value}`;
    } else {
      frontMater[key] = value;
    }
  }
  return frontMater;
}
function replaceVariableSyntax(book, text) {
  if (!(text == null ? void 0 : text.trim())) {
    return "";
  }
  const data = book;
  const result = text.replace(/{{(?:(\w+):)?(\w+)}}/gi, (_match, modifier, key) => {
    const lowerKey = key.toLowerCase();
    const bookKey = Object.keys(data).find((k) => k.toLowerCase() === lowerKey);
    if (bookKey === void 0)
      return "";
    const val = data[bookKey];
    if (!modifier) {
      return val != null ? Array.isArray(val) ? val.join(",") : safeToString(val) : "";
    }
    const mod = modifier.toLowerCase();
    if (mod === "list") {
      if (!Array.isArray(val)) {
        return val != null ? `
  - ${safeToString(val)}` : "";
      }
      if (val.length === 0)
        return "";
      return val.map((item) => `
  - ${safeToString(item)}`).join("");
    }
    if (mod === "enum") {
      if (!Array.isArray(val)) {
        return val != null ? safeToString(val) : "";
      }
      return val.map((item) => safeToString(item)).join(", ");
    }
    if (mod === "wikilist") {
      if (!Array.isArray(val)) {
        const safe = safeToString(val != null ? val : "").replace(/[\]"[]/g, "");
        return val != null ? `
  - "[[${safe}]]"` : "";
      }
      if (val.length === 0)
        return "";
      return val.map((item) => {
        const safe = safeToString(item).replace(/[\]"[]/g, "");
        return `
  - "[[${safe}]]"`;
      }).join("");
    }
    return "";
  });
  return result.replace(/\s+$/, "");
}
function camelToSnakeCase(str) {
  return str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
}
function parseFrontMatter(frontMatterString) {
  if (!frontMatterString)
    return {};
  return frontMatterString.split("\n").map((item) => {
    var _a, _b;
    const index = item.indexOf(":");
    if (index === -1)
      return [item.trim(), ""];
    const key = (_a = item.slice(0, index)) == null ? void 0 : _a.trim();
    const value = (_b = item.slice(index + 1)) == null ? void 0 : _b.trim();
    return [key, value];
  }).reduce((acc, [key, value]) => {
    var _a;
    if (key) {
      acc[key] = (_a = value == null ? void 0 : value.trim()) != null ? _a : "";
    }
    return acc;
  }, {});
}
function toStringFrontMatter(frontMatter) {
  return Object.entries(frontMatter).map(([key, value]) => {
    if (Array.isArray(value)) {
      if (value.length === 0)
        return "";
      const items = value.filter((item) => !/\r|\n/.test(String(item))).map((item) => {
        const s = String(item);
        if (/:/.test(s)) {
          return `  - "${s.replace(/"/g, "&quot;")}"`;
        }
        return `  - ${s}`;
      });
      if (items.length === 0)
        return "";
      return `${key}:
${items.join("\n")}
`;
    }
    const newValue = value != null ? String(value).trim() : "";
    if (/\r|\n/.test(newValue)) {
      return "";
    }
    if (/:/.test(newValue)) {
      return `${key}: "${newValue.replace(/"/g, "&quot;")}"
`;
    }
    return `${key}: ${newValue}
`;
  }).join("").trim();
}
function getDate(input) {
  let duration;
  if ((input == null ? void 0 : input.offset) !== null && (input == null ? void 0 : input.offset) !== void 0 && typeof input.offset === "number") {
    duration = import_obsidian3.moment.duration(input.offset, "days");
  }
  const m = window.moment;
  return (input == null ? void 0 : input.format) ? m().add(duration).format(input.format) : m().add(duration).format("YYYY-MM-DD");
}
function replaceDateInString(input) {
  let output = input;
  while (DATE_REGEX.test(output)) {
    const dateMatch = DATE_REGEX.exec(output);
    let offset = 0;
    if (dateMatch == null ? void 0 : dateMatch[1]) {
      const offsetString = dateMatch[1].replace("+", "").trim();
      const offsetIsInt = NUMBER_REGEX.test(offsetString);
      if (offsetIsInt)
        offset = parseInt(offsetString);
    }
    output = replacer(output, DATE_REGEX, getDate({ offset }));
  }
  while (DATE_REGEX_FORMATTED.test(output)) {
    const dateMatch = DATE_REGEX_FORMATTED.exec(output);
    const format = dateMatch == null ? void 0 : dateMatch[1];
    let offset = 0;
    if (dateMatch == null ? void 0 : dateMatch[2]) {
      const offsetString = dateMatch[2].replace("+", "").trim();
      const offsetIsInt = NUMBER_REGEX.test(offsetString);
      if (offsetIsInt)
        offset = parseInt(offsetString);
    }
    output = replacer(output, DATE_REGEX_FORMATTED, getDate({ format, offset }));
  }
  return output;
}
function replacer(str, reg, replaceValue) {
  return str.replace(reg, function() {
    return replaceValue;
  });
}

// src/settings/settings.ts
var import_obsidian8 = require("obsidian");

// src/utils/languages.ts
var languages = {
  en: "English",
  af: "Afrikaans",
  "ar-dz": "Arabic (Algeria)",
  "ar-kw": "Arabic (Kuwait)",
  "ar-ly": "Arabic (Libya)",
  "ar-ma": "Arabic (Morocco)",
  "ar-sa": "Arabic (Saudi Arabia)",
  "ar-tn": "Arabic (Tunisia)",
  ar: "Arabic",
  az: "Azerbaijani",
  be: "Belarusian",
  bg: "Bulgarian",
  bm: "Bambara",
  bn: "Bengali",
  bo: "Tibetan",
  br: "Breton",
  bs: "Bosnian",
  ca: "Catalan",
  cs: "Czech",
  cv: "Chuvash",
  cy: "Welsh",
  da: "Danish",
  "de-at": "German (Austria)",
  "de-ch": "German (Switzerland)",
  de: "German",
  dv: "Divehi",
  el: "Greek",
  "en-au": "English (Australia)",
  "en-ca": "English (Canada)",
  "en-gb": "English (United Kingdom)",
  "en-ie": "English (Ireland)",
  "en-nz": "English (New Zealand)",
  eo: "Esperanto",
  "es-do": "Spanish (Dominican Republic)",
  "es-us": "Spanish (United States)",
  es: "Spanish",
  et: "Estonian",
  eu: "Basque",
  fa: "Persian",
  fi: "Finnish",
  fo: "Faroese",
  "fr-ca": "French (Canada)",
  "fr-ch": "French (Switzerland)",
  fr: "French",
  fy: "Western Frisian",
  gd: "Scottish Gaelic",
  gl: "Galician",
  "gom-latn": "gom (Latin)",
  gu: "Gujarati",
  he: "Hebrew",
  hi: "Hindi",
  hr: "Croatian",
  hu: "Hungarian",
  "hy-am": "Armenian (Armenia)",
  id: "Indonesian",
  is: "Icelandic",
  it: "Italian",
  ja: "Japanese",
  jv: "Javanese",
  ka: "Georgian",
  kk: "Kazakh",
  km: "Khmer",
  kn: "Kannada",
  ko: "Korean",
  ky: "Kirghiz",
  lb: "Luxembourgish",
  lo: "Lao",
  lt: "Lithuanian",
  lv: "Latvian",
  me: "me",
  mi: "Maori",
  mk: "Macedonian",
  ml: "Malayalam",
  mr: "Marathi",
  "ms-my": "Malay (Malaysia)",
  ms: "Malay",
  mt: "Maltese",
  my: "Burmese",
  nb: "Norwegian Bokm\xE5l",
  ne: "Nepali",
  "nl-be": "Dutch (Belgium)",
  nl: "Dutch",
  nn: "Norwegian Nynorsk",
  "pa-in": "Punjabi (India)",
  pl: "Polish",
  "pt-br": "Portuguese (Brazil)",
  pt: "Portuguese",
  ro: "Romanian",
  ru: "Russian",
  sd: "Sindhi",
  se: "Northern Sami",
  si: "Sinhala",
  sk: "Slovak",
  sl: "Slovenian",
  sq: "Albanian",
  "sr-cyrl": "Serbian (Cyrillic)",
  sr: "Serbian",
  ss: "Swati",
  sv: "Swedish",
  sw: "Swahili",
  ta: "Tamil",
  te: "Telugu",
  tet: "Tetum",
  th: "Thai",
  "tl-ph": "Tagalog (Philippines)",
  tlh: "Klingon",
  tr: "Turkish",
  tzl: "tzl",
  "tzm-latn": "tzm (Latin)",
  tzm: "tzm",
  uk: "Ukrainian",
  ur: "Urdu",
  "uz-latn": "Uzbek (Latin)",
  uz: "Uzbek",
  vi: "Vietnamese",
  "x-pseudo": "x-pseudo",
  yo: "Yoruba",
  "zh-cn": "Chinese (China)",
  "zh-hk": "Chinese (Hong Kong SAR China)",
  "zh-tw": "Chinese (Taiwan)",
  "zh-mo": "Chinese (Macau SAR China)"
};
var languages_default = languages;

// src/views/setting_service_provider_modal.ts
var import_obsidian4 = require("obsidian");
var SettingServiceProviderModal = class extends import_obsidian4.Modal {
  constructor(plugin, callback) {
    var _a, _b;
    super(plugin.app);
    this.callback = callback;
    this.plugin = plugin;
    this.currentServiceProvider = (_b = (_a = plugin.settings) == null ? void 0 : _a.serviceProvider) != null ? _b : "google" /* google */;
  }
  get settings() {
    return this.plugin.settings;
  }
  async saveSetting() {
    return this.plugin.saveSettings();
  }
  saveClientId(clientId) {
    if (this.currentServiceProvider === "naver" /* naver */) {
      this.plugin.settings["naverClientId"] = clientId;
    }
  }
  saveClientSecret(clientSecret) {
    if (this.currentServiceProvider === "naver" /* naver */) {
      this.settings["naverClientSecret"] = clientSecret;
    }
  }
  get currentClientId() {
    if (this.currentServiceProvider === "naver" /* naver */) {
      return this.settings.naverClientId;
    }
    return "";
  }
  get currentClientSecret() {
    if (this.currentServiceProvider === "naver" /* naver */) {
      return this.settings.naverClientSecret;
    }
    return "";
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Service provider setting" });
    new import_obsidian4.Setting(contentEl).setName("Client ID").addText((text) => {
      text.setValue(this.currentClientId).onChange((value) => this.saveClientId(value));
    });
    new import_obsidian4.Setting(contentEl).setName("Client secret").addText((text) => {
      text.inputEl.type = "password";
      text.setValue(this.currentClientSecret).onChange((value) => this.saveClientSecret(value));
    });
    new import_obsidian4.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Save").setCta().onClick(async () => {
        var _a;
        await this.plugin.saveSettings();
        this.close();
        (_a = this.callback) == null ? void 0 : _a.call(this);
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings/suggesters/FileNameFormatSuggester.ts
var import_obsidian5 = require("obsidian");
var DATE_SYNTAX = "{{DATE}}";
var DATE_FORMAT_SYNTAX = "{{DATE:}}";
var DATE_SYNTAX_SUGGEST_REGEX = /{{D?A?T?E?}?}?$/i;
var DATE_FORMAT_SYNTAX_SUGGEST_REGEX = /{{D?A?T?E?:?$|{{DATE:[^\n\r}]*}}$/i;
var AUTHOR_SYNTAX = "{{author}}";
var AUTHOR_SYNTAX_SUGGEST_REGEX = /{{a?u?t?h?o?r?}?}?$/i;
var TITLE_SYNTAX = "{{title}}";
var TITLE_SYNTAX_SUGGEST_REGEX = /{{t?i?t?l?e?}?}?$/i;
var FileNameFormatSuggest = class extends import_obsidian5.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.lastInput = "";
    this.inputEl = inputEl;
  }
  getSuggestions(inputStr) {
    var _a;
    const cursorPosition = (_a = this.inputEl.selectionStart) != null ? _a : 0;
    const lookbehind = 15;
    const inputBeforeCursor = inputStr.substring(cursorPosition - lookbehind, cursorPosition);
    const suggestions = [];
    this.processToken(inputBeforeCursor, (match, suggestion) => {
      this.lastInput = match[0];
      suggestions.push(suggestion);
    });
    return suggestions;
  }
  selectSuggestion(item, _evt) {
    var _a;
    const cursorPosition = (_a = this.inputEl.selectionStart) != null ? _a : 0;
    const lastInputLength = this.lastInput.length;
    const currentInputValue = this.inputEl.value;
    let insertedEndPosition = 0;
    const insert = (text, offset = 0) => {
      return `${currentInputValue.substring(0, cursorPosition - lastInputLength + offset)}${text}${currentInputValue.substring(cursorPosition)}`;
    };
    this.processToken(item, (_match, suggestion) => {
      if (item.contains(suggestion)) {
        this.setValue(insert(item));
        insertedEndPosition = cursorPosition - lastInputLength + item.length;
        if (item === DATE_FORMAT_SYNTAX) {
          insertedEndPosition -= 2;
        }
      }
    });
    this.inputEl.trigger("input");
    this.close();
    this.inputEl.setSelectionRange(insertedEndPosition, insertedEndPosition);
  }
  renderSuggestion(value, el) {
    if (value)
      el.setText(value);
  }
  processToken(input, callback) {
    const dateFormatMatch = DATE_FORMAT_SYNTAX_SUGGEST_REGEX.exec(input);
    if (dateFormatMatch)
      callback(dateFormatMatch, DATE_FORMAT_SYNTAX);
    const dateMatch = DATE_SYNTAX_SUGGEST_REGEX.exec(input);
    if (dateMatch)
      callback(dateMatch, DATE_SYNTAX);
    const authorMatch = AUTHOR_SYNTAX_SUGGEST_REGEX.exec(input);
    if (authorMatch)
      callback(authorMatch, AUTHOR_SYNTAX);
    const titleMatch = TITLE_SYNTAX_SUGGEST_REGEX.exec(input);
    if (titleMatch)
      callback(titleMatch, TITLE_SYNTAX);
  }
};

// src/settings/suggesters/FileSuggester.ts
var import_obsidian6 = require("obsidian");
var FileSuggest = class extends import_obsidian6.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const files = [];
    const lowerCaseInputStr = inputStr.toLowerCase();
    abstractFiles.forEach((file) => {
      if (file instanceof import_obsidian6.TFile && file.extension === "md" && file.path.toLowerCase().contains(lowerCaseInputStr)) {
        files.push(file);
      }
    });
    return files;
  }
  renderSuggestion(file, el) {
    el.setText(file.path);
  }
  selectSuggestion(file, _evt) {
    this.setValue(file.path);
    this.inputEl.trigger("input");
    this.close();
  }
};

// src/settings/suggesters/FolderSuggester.ts
var import_obsidian7 = require("obsidian");
var FolderSuggest = class extends import_obsidian7.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const folders = [];
    const lowerCaseInputStr = inputStr.toLowerCase();
    abstractFiles.forEach((folder) => {
      if (folder instanceof import_obsidian7.TFolder && folder.path.toLowerCase().contains(lowerCaseInputStr)) {
        folders.push(folder);
      }
    });
    return folders;
  }
  renderSuggestion(file, el) {
    el.setText(file.path);
  }
  selectSuggestion(file, _evt) {
    this.setValue(file.path);
    this.inputEl.trigger("input");
    this.close();
  }
};

// src/settings/settings.ts
var docUrl = "https://github.com/anpigon/obsidian-book-search-plugin";
var DEFAULT_SETTINGS = {
  folder: "",
  fileNameFormat: "",
  frontmatter: "",
  content: "",
  useDefaultFrontmatter: true,
  defaultFrontmatterKeyType: "Camel Case" /* camelCase */,
  templateFile: "",
  serviceProvider: "google" /* google */,
  naverClientId: "",
  naverClientSecret: "",
  localePreference: "default",
  apiKey: "",
  openPageOnCompletion: true,
  showCoverImageInSearch: false,
  enableCoverImageSave: false,
  enableCoverImageEdgeCurl: true,
  coverImagePath: "",
  askForLocale: true
};
var BookSearchSettingTab = class extends import_obsidian8.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  createGeneralSettings(containerEl) {
    this.createHeader("General settings", containerEl);
    this.createFileLocationSetting(containerEl);
    this.createFileNameFormatSetting(containerEl);
  }
  createHeader(title, containerEl) {
    return new import_obsidian8.Setting(containerEl).setName(title).setHeading();
  }
  createFileLocationSetting(containerEl) {
    new import_obsidian8.Setting(containerEl).setName("New file location").setDesc("New book notes will be placed here.").addSearch((cb) => {
      try {
        new FolderSuggest(this.app, cb.inputEl);
      } catch (e) {
        console.error(e);
      }
      cb.setPlaceholder("Example: folder1/folder2").setValue(this.plugin.settings.folder).onChange((new_folder) => {
        this.plugin.settings.folder = new_folder;
        void this.plugin.saveSettings();
      });
    });
  }
  createFileNameFormatSetting(containerEl) {
    const hintFrag = createFragment();
    const newFileNameHint = hintFrag.createEl("code", {
      text: replaceDateInString(this.plugin.settings.fileNameFormat) || "{{title}} - {{author}}"
    });
    new import_obsidian8.Setting(containerEl).setClass("book-search-plugin__settings--new_file_name").setName("New file name").setDesc("Enter the file name format.").addSearch((cb) => {
      try {
        new FileNameFormatSuggest(this.app, cb.inputEl);
      } catch (e) {
        console.error(e);
      }
      cb.setPlaceholder("Example: {{title}} - {{author}}").setValue(this.plugin.settings.fileNameFormat).onChange((newValue) => {
        this.plugin.settings.fileNameFormat = newValue == null ? void 0 : newValue.trim();
        void this.plugin.saveSettings();
        newFileNameHint.textContent = replaceDateInString(newValue) || "{{title}} - {{author}}";
      });
    });
    containerEl.createDiv({
      cls: ["setting-item-description", "book-search-plugin__settings--new_file_name_hint"]
    }).append(newFileNameHint);
  }
  createTemplateFileSetting(containerEl) {
    const templateFileDesc = createFragment();
    templateFileDesc.createDiv({ text: "Files will be available as templates." });
    templateFileDesc.createEl("a", {
      text: "Example template",
      href: `${docUrl}#example-template`
    });
    new import_obsidian8.Setting(containerEl).setName("Template file").setDesc(templateFileDesc).addSearch((cb) => {
      try {
        new FileSuggest(this.app, cb.inputEl);
      } catch (e) {
      }
      cb.setPlaceholder("Example: templates/template-file").setValue(this.plugin.settings.templateFile).onChange((newTemplateFile) => {
        this.plugin.settings.templateFile = newTemplateFile;
        void this.plugin.saveSettings();
      });
    });
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.classList.add("book-search-plugin__settings");
    this.createGeneralSettings(containerEl);
    this.createTemplateFileSetting(containerEl);
    let serviceProviderExtraSettingButton;
    let preferredLocaleDropdownSetting;
    let coverImageEdgeCurlToggleSetting;
    const hideServiceProviderExtraSettingButton = () => {
      serviceProviderExtraSettingButton.addClass("book-search-plugin__hide");
    };
    const showServiceProviderExtraSettingButton = () => {
      serviceProviderExtraSettingButton.removeClass("book-search-plugin__hide");
    };
    const hideServiceProviderExtraSettingDropdown = () => {
      if (preferredLocaleDropdownSetting !== void 0) {
        preferredLocaleDropdownSetting.settingEl.addClass("book-search-plugin__hide");
      }
    };
    const showServiceProviderExtraSettingDropdown = () => {
      if (preferredLocaleDropdownSetting !== void 0) {
        preferredLocaleDropdownSetting.settingEl.removeClass("book-search-plugin__hide");
      }
    };
    const hideCoverImageEdgeCurlToggle = () => {
      if (coverImageEdgeCurlToggleSetting !== void 0) {
        coverImageEdgeCurlToggleSetting.settingEl.addClass("book-search-plugin__hide");
      }
    };
    const showCoverImageEdgeCurlToggle = () => {
      if (coverImageEdgeCurlToggleSetting !== void 0) {
        coverImageEdgeCurlToggleSetting.settingEl.removeClass("book-search-plugin__hide");
      }
    };
    const toggleServiceProviderExtraSettings = (serviceProvider = ((_a) => (_a = this.plugin.settings) == null ? void 0 : _a.serviceProvider)()) => {
      if (serviceProvider === "naver" /* naver */) {
        showServiceProviderExtraSettingButton();
        hideServiceProviderExtraSettingDropdown();
        hideCoverImageEdgeCurlToggle();
      } else {
        hideServiceProviderExtraSettingButton();
        showServiceProviderExtraSettingDropdown();
        showCoverImageEdgeCurlToggle();
      }
    };
    new import_obsidian8.Setting(containerEl).setName("Service provider").setDesc("Choose the service provider you want to use to search your books.").setClass("book-search-plugin__settings--service_provider").addDropdown((dropDown) => {
      var _a, _b;
      dropDown.addOption("google" /* google */, `${"google" /* google */} (Global)`);
      dropDown.addOption("naver" /* naver */, `${"naver" /* naver */} (Korean)`);
      dropDown.setValue((_b = (_a = this.plugin.settings) == null ? void 0 : _a.serviceProvider) != null ? _b : "google" /* google */);
      dropDown.onChange(async (value) => {
        const newValue = value;
        toggleServiceProviderExtraSettings(newValue);
        this.plugin.settings["serviceProvider"] = newValue;
        await this.plugin.saveSettings();
      });
    }).addExtraButton((component) => {
      serviceProviderExtraSettingButton = component.extraSettingsEl;
      toggleServiceProviderExtraSettings();
      component.onClick(() => {
        new SettingServiceProviderModal(this.plugin).open();
      });
    });
    preferredLocaleDropdownSetting = new import_obsidian8.Setting(containerEl).setName("Preferred locale").setDesc("Sets the preferred locale to use when searching for books.").addDropdown((dropDown) => {
      var _a;
      const langs = languages_default;
      const defaultLocale = import_obsidian8.moment.locale();
      dropDown.addOption(defaultLocale, `${(_a = langs[defaultLocale]) != null ? _a : defaultLocale} (Default Locale)`);
      import_obsidian8.moment.locales().forEach((locale) => {
        const localeName = langs[locale];
        if (localeName && locale !== defaultLocale)
          dropDown.addOption(locale, localeName);
      });
      const localeValue = this.plugin.settings.localePreference;
      dropDown.setValue(localeValue === DEFAULT_SETTINGS.localePreference ? defaultLocale : localeValue).onChange(async (value) => {
        const newValue = value;
        this.plugin.settings.localePreference = newValue;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian8.Setting(containerEl).setName("Open new book note").setDesc("Enable or disable the automatic opening of the note on creation.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.openPageOnCompletion).onChange(async (value) => {
        this.plugin.settings.openPageOnCompletion = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian8.Setting(containerEl).setName("Show cover images in search").setDesc("Toggle to show or hide cover images in the search results.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showCoverImageInSearch).onChange(async (value) => {
        this.plugin.settings.showCoverImageInSearch = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian8.Setting(containerEl).setName("Ask for locale").setDesc("Toggle to enable or disable asking for the locale every time a search is made.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.askForLocale).onChange(async (value) => {
        this.plugin.settings.askForLocale = value;
        await this.plugin.saveSettings();
      })
    );
    coverImageEdgeCurlToggleSetting = new import_obsidian8.Setting(containerEl).setName("Enable cover image edge curl effect").setDesc("Toggle to show or hide page curl effect in cover images.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableCoverImageEdgeCurl).onChange(async (value) => {
        this.plugin.settings.enableCoverImageEdgeCurl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian8.Setting(containerEl).setName("Enable cover image save").setDesc("Toggle to enable or disable saving cover images in notes.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableCoverImageSave).onChange(async (value) => {
        this.plugin.settings.enableCoverImageSave = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian8.Setting(containerEl).setName("Cover image path").setDesc("Specify the path where cover images should be saved.").addSearch((cb) => {
      try {
        new FolderSuggest(this.app, cb.inputEl);
      } catch (e) {
      }
      cb.setPlaceholder("Enter the path (e.g., images/covers)").setValue(this.plugin.settings.coverImagePath).onChange(async (value) => {
        this.plugin.settings.coverImagePath = value.trim();
        await this.plugin.saveSettings();
      });
    });
    this.createHeader("Google API settings", containerEl);
    new import_obsidian8.Setting(containerEl).setName("Google API note").setDesc("Use this field only after understanding Google cloud API key security.");
    new import_obsidian8.Setting(containerEl).setName("Status check").setDesc("Check whether API key is saved. It does not guarantee that the API key is valid or invalid.").addButton((button) => {
      button.setButtonText("API check").onClick(() => {
        if (this.plugin.settings.apiKey.length) {
          new import_obsidian8.Notice("API key exists.");
        } else {
          new import_obsidian8.Notice("API key does not exist.");
        }
      });
    });
    const googleAPISetDesc = createFragment();
    googleAPISetDesc.createDiv({ text: "Set your Books API key." });
    googleAPISetDesc.createDiv({
      text: "For security reasons, a saved key is not shown after it is stored."
    });
    let tempKeyValue = "";
    let textComponent;
    let saveButton;
    const hasKey = () => !!this.plugin.settings.apiKey;
    const applyKeyState = () => {
      if (hasKey()) {
        textComponent.inputEl.placeholder = "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022";
        textComponent.inputEl.disabled = true;
        textComponent.setValue("");
        saveButton.setButtonText("Clear key").setClass("mod-warning").setDisabled(false);
      } else {
        textComponent.inputEl.placeholder = "";
        textComponent.inputEl.disabled = false;
        saveButton.setButtonText("Save key").setDisabled(false);
        saveButton.buttonEl.removeClass("mod-warning");
      }
    };
    new import_obsidian8.Setting(containerEl).setName("Set API key").setDesc(googleAPISetDesc).addText((text) => {
      textComponent = text;
      text.inputEl.type = "password";
      text.setValue("").onChange((value) => {
        tempKeyValue = value;
      });
    }).addButton((button) => {
      saveButton = button;
      button.onClick(async () => {
        if (hasKey()) {
          this.plugin.settings.apiKey = "";
          tempKeyValue = "";
          await this.plugin.saveSettings();
          applyKeyState();
        } else {
          this.plugin.settings.apiKey = tempKeyValue;
          await this.plugin.saveSettings();
          button.setButtonText("Key saved").setDisabled(true);
          activeWindow.setTimeout(() => applyKeyState(), 2e3);
        }
      });
      applyKeyState();
    });
  }
};

// src/views/book_search_modal.ts
var import_obsidian9 = require("obsidian");

// src/views/rate_limit_notice.ts
var API_KEY_DOCS_URL = "https://github.com/curtismchale/obsidian-book-search-plus#how-to-add-an-api-key-to-bypass-rate-limits";
function buildRateLimitNoticeFragment(hasApiKey) {
  return createFragment((fragment) => {
    fragment.appendText("Google Books rate limit reached. ");
    if (hasApiKey) {
      fragment.appendText("Wait a moment and try again.");
      return;
    }
    fragment.createEl("a", {
      text: "Add a Google books API key",
      href: API_KEY_DOCS_URL,
      attr: { target: "_blank", rel: "noopener noreferrer" }
    });
    fragment.appendText(" for a higher quota, or wait a moment and try again.");
  });
}

// src/views/book_search_modal.ts
var BookSearchModal = class extends import_obsidian9.Modal {
  constructor(plugin, query, callback) {
    super(plugin.app);
    this.plugin = plugin;
    this.query = query;
    this.callback = callback;
    this.SEARCH_BUTTON_TEXT = "Search";
    this.REQUESTING_BUTTON_TEXT = "Requesting...";
    this.isBusy = false;
    this.options = { locale: plugin.settings.localePreference };
    this.serviceProvider = factoryServiceProvider(plugin.settings);
  }
  setBusy(busy) {
    var _a;
    this.isBusy = busy;
    (_a = this.okBtnRef) == null ? void 0 : _a.setDisabled(busy).setButtonText(busy ? this.REQUESTING_BUTTON_TEXT : this.SEARCH_BUTTON_TEXT);
  }
  async searchBook() {
    if (!this.query)
      return void new import_obsidian9.Notice("No query entered.");
    if (this.isBusy)
      return;
    this.setBusy(true);
    let shouldClose = true;
    try {
      const searchResults = await this.serviceProvider.getByQuery(this.query, this.options);
      if (!(searchResults == null ? void 0 : searchResults.length))
        return void new import_obsidian9.Notice(`No results found for "${this.query}"`);
      this.callback(null, searchResults);
    } catch (err) {
      const status = err.status;
      if (status === 429) {
        shouldClose = false;
        new import_obsidian9.Notice(buildRateLimitNoticeFragment(!!this.plugin.settings.apiKey), 8e3);
      } else {
        this.callback(err);
      }
    } finally {
      this.setBusy(false);
      if (shouldClose)
        this.close();
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Search book" });
    if (this.plugin.settings.serviceProvider === "google" /* google */ && this.plugin.settings.askForLocale)
      this.renderSelectLocale();
    contentEl.createDiv({ cls: "book-search-plugin__search-modal--input" }, (el) => {
      const textComponent = new import_obsidian9.TextComponent(el).setValue(this.query).setPlaceholder("Search by keyword or isbn").onChange((value) => this.query = value);
      textComponent.inputEl.addEventListener("keydown", (event) => {
        if (event.key === "Enter" && !event.isComposing) {
          void this.searchBook();
        }
      });
      activeWindow.setTimeout(() => textComponent.inputEl.focus(), 0);
    });
    new import_obsidian9.Setting(this.contentEl).addButton((btn) => {
      this.okBtnRef = btn.setButtonText(this.SEARCH_BUTTON_TEXT).setCta().onClick(() => {
        void this.searchBook();
      });
    });
  }
  renderSelectLocale() {
    const langs = languages_default;
    const defaultLocale = import_obsidian9.moment.locale();
    new import_obsidian9.Setting(this.contentEl).setName("Locale").addDropdown((dropdown) => {
      var _a;
      dropdown.addOption(defaultLocale, `${(_a = langs[defaultLocale]) != null ? _a : defaultLocale}`);
      import_obsidian9.moment.locales().forEach((locale) => {
        const localeName = langs[locale];
        if (localeName && locale !== defaultLocale)
          dropdown.addOption(locale, localeName);
      });
      dropdown.setValue(this.options.locale === DEFAULT_SETTINGS.localePreference ? defaultLocale : this.options.locale).onChange((locale) => this.options.locale = locale);
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/views/book_suggest_modal.ts
var import_obsidian10 = require("obsidian");
var BookSuggestModal = class extends import_obsidian10.SuggestModal {
  constructor(app, showCoverImageInSearch, suggestion, onChoose) {
    super(app);
    this.suggestion = suggestion;
    this.onChoose = onChoose;
    this.showCoverImageInSearch = showCoverImageInSearch;
  }
  // Returns all available suggestions.
  getSuggestions(query) {
    return this.suggestion.filter((book) => {
      var _a, _b, _c;
      const searchQuery = query == null ? void 0 : query.toLowerCase();
      return ((_a = book.title) == null ? void 0 : _a.toLowerCase().includes(searchQuery)) || ((_b = book.author) == null ? void 0 : _b.toLowerCase().includes(searchQuery)) || ((_c = book.publisher) == null ? void 0 : _c.toLowerCase().includes(searchQuery));
    });
  }
  // Renders each suggestion item.
  renderSuggestion(book, el) {
    el.addClass("book-suggestion-item");
    const coverImageUrl = book.coverLargeUrl || book.coverMediumUrl || book.coverSmallUrl || book.coverUrl;
    if (this.showCoverImageInSearch && coverImageUrl) {
      el.createEl("img", {
        cls: "book-cover-image",
        attr: {
          src: coverImageUrl,
          alt: `Cover Image for ${book.title}`
        }
      });
    }
    const textContainer = el.createDiv({ cls: "book-text-info" });
    textContainer.createDiv({ text: book.title });
    const publisher = book.publisher ? `, ${book.publisher}` : "";
    const publishDate = book.publishDate ? `(${book.publishDate})` : "";
    const totalPage = book.totalPage ? `, p${book.totalPage}` : "";
    const subtitle = `${book.author}${publisher}${publishDate}${totalPage}`;
    textContainer.createEl("small", { text: subtitle });
  }
  // Perform action on the selected suggestion.
  onChooseSuggestion(book) {
    this.onChoose(null, book);
  }
};

// src/utils/cursor_jumper.ts
var import_obsidian11 = require("obsidian");
var CursorJumper = class {
  constructor(app) {
    this.app = app;
  }
  async jumpToNextCursorLocation() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian11.MarkdownView);
    if (!activeView) {
      return;
    }
    const content = await this.app.vault.cachedRead(activeView.file);
    const indexOffset = content.length + 1;
    const editor = activeView.editor;
    editor.focus();
    editor.setCursor(indexOffset, 0);
  }
};

// src/utils/template.ts
var import_obsidian12 = require("obsidian");
async function getTemplateContents(app, templatePath) {
  const { metadataCache, vault } = app;
  const normalizedTemplatePath = (0, import_obsidian12.normalizePath)(templatePath != null ? templatePath : "");
  if (templatePath === "/") {
    return Promise.resolve("");
  }
  try {
    const templateFile = metadataCache.getFirstLinkpathDest(normalizedTemplatePath, "");
    return templateFile ? vault.cachedRead(templateFile) : "";
  } catch (err) {
    console.error(`Failed to read the daily note template '${normalizedTemplatePath}'`, err);
    new import_obsidian12.Notice("Failed to read the daily note template");
    return "";
  }
}
function applyTemplateTransformations(rawTemplateContents) {
  return rawTemplateContents.replace(
    /{{\s*(date|time)\s*(([+-]\d+)([yqmwdhs]))?\s*(:.+?)?}}/gi,
    (_, _timeOrDate, calc, timeDelta, unit, momentFormat) => {
      const m = window.moment;
      const now = m();
      const currentDate = m().clone().set({
        hour: now.get("hour"),
        minute: now.get("minute"),
        second: now.get("second")
      });
      if (calc) {
        currentDate.add(parseInt(timeDelta, 10), unit);
      }
      if (momentFormat) {
        return currentDate.format(momentFormat.substring(1).trim());
      }
      return currentDate.format("YYYY-MM-DD");
    }
  );
}
function safeToString2(value) {
  if (value == null)
    return "";
  if (typeof value === "string")
    return value;
  if (typeof value === "number" || typeof value === "boolean")
    return String(value);
  return JSON.stringify(value);
}
function evaluateBookExpression(book, script) {
  var _a, _b;
  const trimmed = script.trim();
  const bookRecord = book;
  const orStringMatch = trimmed.match(/^book\.(\w+)\s*\|\|\s*(?:"([^"]*)"|'([^']*)')$/);
  if (orStringMatch) {
    const value = bookRecord[orStringMatch[1]];
    const fallback = (_b = (_a = orStringMatch[2]) != null ? _a : orStringMatch[3]) != null ? _b : "";
    return value ? safeToString2(value) : fallback;
  }
  const orPropMatch = trimmed.match(/^book\.(\w+)\s*\|\|\s*book\.(\w+)$/);
  if (orPropMatch) {
    const value1 = bookRecord[orPropMatch[1]];
    const value2 = bookRecord[orPropMatch[2]];
    return value1 ? safeToString2(value1) : safeToString2(value2);
  }
  const propMatch = trimmed.match(/^book\.(\w+)$/);
  if (propMatch) {
    return safeToString2(bookRecord[propMatch[1]]);
  }
  console.warn(`Unsupported inline script expression: ${trimmed}`);
  return "";
}
function executeInlineScriptsTemplates(book, text) {
  return text.replace(/<%=\s*(.+?)\s*%>/g, (_match, script) => {
    try {
      return evaluateBookExpression(book, script);
    } catch (err) {
      console.warn(err);
      return _match;
    }
  });
}
async function useTemplaterPluginInFile(app, file) {
  const appWithPlugins = app;
  const templater = appWithPlugins.plugins.plugins["templater-obsidian"];
  if (templater && !templater.settings["trigger_on_file_creation"]) {
    await templater.templater.overwrite_file_commands(file);
  }
}

// src/main.ts
var BookSearchPlugin = class extends import_obsidian13.Plugin {
  onload() {
    void this.initialize();
  }
  async initialize() {
    await this.loadSettings();
    const ribbonIconEl = this.addRibbonIcon("book", "Create new book note", () => {
      void this.createNewBookNote();
    });
    ribbonIconEl.addClass("obsidian-book-search-plugin-ribbon-class");
    this.addCommand({
      id: "open-book-search-modal",
      name: "Create new book note",
      callback: () => {
        void this.createNewBookNote();
      }
    });
    this.addCommand({
      id: "open-book-search-modal-to-insert",
      name: "Insert the metadata",
      callback: () => {
        void this.insertMetadata();
      }
    });
    this.addSettingTab(new BookSearchSettingTab(this.app, this));
    console.debug(`Book Search: version ${this.manifest.version} (requires obsidian ${this.manifest.minAppVersion})`);
  }
  showNotice(message) {
    try {
      let text;
      if (message instanceof Error) {
        text = message.message;
      } else if (typeof message === "string") {
        text = message;
      } else if (message != null) {
        text = JSON.stringify(message);
      } else {
        text = "";
      }
      new import_obsidian13.Notice(text);
    } catch (e) {
    }
  }
  // open modal for book search
  async searchBookMetadata(query) {
    const searchedBooks = await this.openBookSearchModal(query);
    return await this.openBookSuggestModal(searchedBooks);
  }
  async getRenderedContents(book) {
    const {
      templateFile,
      useDefaultFrontmatter,
      defaultFrontmatterKeyType,
      enableCoverImageSave,
      coverImagePath,
      frontmatter,
      // @deprecated
      content
      // @deprecated
    } = this.settings;
    let contentBody = "";
    if (enableCoverImageSave) {
      const coverImageUrl = book.coverLargeUrl || book.coverMediumUrl || book.coverSmallUrl || book.coverUrl;
      if (coverImageUrl) {
        const imageName = makeFileName(book, this.settings.fileNameFormat, "jpg");
        book.localCoverImage = await this.downloadAndSaveImage(imageName, coverImagePath, coverImageUrl);
      }
    }
    if (templateFile) {
      const templateContents = await getTemplateContents(this.app, templateFile);
      const replacedVariable = replaceVariableSyntax(book, applyTemplateTransformations(templateContents));
      contentBody += executeInlineScriptsTemplates(book, replacedVariable);
    } else {
      let replacedVariableFrontmatter = replaceVariableSyntax(book, frontmatter);
      if (useDefaultFrontmatter) {
        replacedVariableFrontmatter = toStringFrontMatter(
          applyDefaultFrontMatter(book, replacedVariableFrontmatter, defaultFrontmatterKeyType)
        );
      }
      const replacedVariableContent = replaceVariableSyntax(book, content);
      contentBody += replacedVariableFrontmatter ? `---
${replacedVariableFrontmatter}
---
${replacedVariableContent}` : replacedVariableContent;
    }
    return contentBody;
  }
  async downloadAndSaveImage(imageName, directory, imageUrl) {
    const { enableCoverImageSave } = this.settings;
    if (!enableCoverImageSave) {
      console.warn("Cover image saving is not enabled.");
      return "";
    }
    try {
      const response = await (0, import_obsidian13.requestUrl)({
        url: imageUrl,
        method: "GET",
        headers: {
          Accept: "image/*"
        }
      });
      if (response.status !== 200) {
        throw new Error(`Failed to download image: ${response.status}`);
      }
      const imageData = response.arrayBuffer;
      const filePath = `${directory}/${imageName}`;
      await this.app.vault.adapter.writeBinary(filePath, imageData);
      return filePath;
    } catch (error) {
      console.error("Error downloading or saving image:", error);
      return "";
    }
  }
  async insertMetadata() {
    try {
      const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian13.MarkdownView);
      if (!markdownView) {
        console.warn("Can not find an active markdown view");
        return;
      }
      const book = await this.searchBookMetadata(markdownView.file.basename);
      if (!markdownView.editor) {
        console.warn("Can not find editor from the active markdown view");
        return;
      }
      const renderedContents = await this.getRenderedContents(book);
      markdownView.editor.replaceRange(renderedContents, { line: 0, ch: 0 });
    } catch (err) {
      console.warn(err);
      this.showNotice(err);
    }
  }
  async ensureFolderExists(folderPath) {
    if (!folderPath)
      return;
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder) {
      await this.app.vault.createFolder(folderPath);
    }
  }
  async createNewBookNote() {
    try {
      const book = await this.searchBookMetadata();
      const renderedContents = await this.getRenderedContents(book);
      const fileName = makeFileName(book, this.settings.fileNameFormat);
      const folderPath = this.settings.folder;
      const filePath = `${folderPath}/${fileName}`;
      await this.ensureFolderExists(folderPath);
      const targetFile = await this.app.vault.create(filePath, renderedContents);
      await useTemplaterPluginInFile(this.app, targetFile);
      await this.openNewBookNote(targetFile);
    } catch (err) {
      console.warn(err);
      this.showNotice(err);
    }
  }
  async openNewBookNote(targetFile) {
    if (!this.settings.openPageOnCompletion)
      return;
    const activeLeaf = this.app.workspace.getLeaf();
    if (!activeLeaf) {
      console.warn("No active leaf");
      return;
    }
    await activeLeaf.openFile(targetFile, { state: { mode: "source" } });
    activeLeaf.setEphemeralState({ rename: "all" });
    await new CursorJumper(this.app).jumpToNextCursorLocation();
  }
  async openBookSearchModal(query = "") {
    return new Promise((resolve, reject) => {
      return new BookSearchModal(this, query, (error, results) => {
        return error ? reject(error) : resolve(results);
      }).open();
    });
  }
  async openBookSuggestModal(books) {
    return new Promise((resolve, reject) => {
      return new BookSuggestModal(this.app, this.settings.showCoverImageInSearch, books, (error, selectedBook) => {
        return error ? reject(error) : resolve(selectedBook);
      }).open();
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};


/* nosourcemap */